### PR TITLE
Update UI for user comments sidebar

### PR DESCRIPTION
**Pull request by esvyridov**
PR for https://github.com/umputun/remark42/issues/1084

Error:

image

Loading:

ezgif com-gif-maker

### CODE REVIEW

**Comment by akellbl4** [comment]
@esvyridov thank you for the PR.
Let's try to make some adjustments to the markup.

1. Center the elements vertically (like empty state)
2. Center the elements horizontally.
3. Make the width of `Retry` button by text.

<details>
<summary>Empty state screenshot:</summary>

CleanShot 2021-08-20 at 11 53 13@2x

</details>

**Comment by esvyridov** [comment]
@akellbl4 thank you, will do

**Comment by esvyridov** [comment]
@akellbl4 ready

**Review by akellbl4 — APPROVED** [review]
Good job, thank you ;)

**Pull request merged**
