### PR TITLE
add RTL support

### PR DESCRIPTION
**Pull request by adueck**
This pull request adds support for RTL (right-to-left) languages. By adding `dir=auto` to the relevant inputs, divs and textareas you get automatic support of RTL languages, with no detriment or loss in functionality to LTR languages.

See this excellent summary [PSA: Add dir="auto" to your inputs and textareas.](https://mough.xyz/312/psa-add-dir-auto-to-your-inputs-and-textareas)

**Before:**

Screenshot 2024-07-25 at 10 12 16 PM

**After:**

Screenshot 2024-07-25 at 10 01 30 PM

### CODE REVIEW

**Review by paskal — APPROVED** [review]

**Comment by adueck** [comment]
Thanks for approving this! Looks like there's just an issue with the dependencies for the tests to run?

```
failed to solve: mcr.microsoft.com/playwright:v1.44-jammy: failed to resolve source metadata for mcr.microsoft.com/playwright:v1.44-jammy: mcr.microsoft.com/playwright:v1.44-jammy: not found
```

**Comment by paskal** [comment]
Playwright will be fixed in #1802.

**Comment by paskal** [comment]
@akellbl4 can you please look into pnpm problem? It's not related to the changes in the PR.

**Comment by adueck** [comment]
Hmm, sorry did I do something wrong when I did `pnpm install` in my fork? If you want I could do another fork/pull request without touching pnpm and see if all the checks pass smoothly.

**Comment by paskal** [comment]
You did nothing wrong, I think master branch is broken at the moment.

**Review by paskal — APPROVED** [review]

**Comment by paskal** [comment]
@umputun let's merge this one, seems like checks are broken in master: we will deal with them later.

**Pull request merged**
