### PR TITLE
Add locale Thai language

### PR DESCRIPTION
**Pull request by kaikunz**
th

### CODE REVIEW

**Comment by kaikunz** [comment]
add thai language

**Comment by paskal** [comment]
Thanks a lot for your contribution! Could you please follow the documentation link https://remark42.com/docs/contributing/translations/ to alter other files that need to be changed when you're adding the new language, and test it? Unfortunately, the language won't be available in the web interface with the current state of the PR.

If you can't, it's not a problem; I can merge your changes and do the rest of the work myself.

**Comment by paskal** [comment]
Nevermind, I found your other PR. It's good to go, and we'll merge it shortly. Thank you!

**Review by paskal — APPROVED** [review]

**Comment by umputun** [comment]
thx

**Pull request merged**
