### PR TITLE
feat: Discord OAuth support

### PR DESCRIPTION
**Pull request by mgkbadola**
Completes Discord OAuth integration on frontend. Can only be merged when a new version of go-pkgz/auth is released with Discord OAuth backend support ([reference](https://github.com/go-pkgz/auth/pull/223)).

### CODE REVIEW

**Comment by paskal** [comment]
You can update to latest master of auth package instead and not wait for the version release.

**Comment by mgkbadola** [comment]
I've done the same, thanks.

**Review by paskal — APPROVED** [review]

**Comment by paskal** [comment]
@mgkbadola thanks a lot! Could you please run Remark42 with Discord auth enabled and post a screenshot of how the auth icon looks like and verify that you can log in using that method?

**Comment by badolamgk** [comment]
Hey @paskal 
Here are the screenshots from my trial run.

Able to login and comment via Discord as intended.
Screenshot 2024-11-12 at 9 18 29 PM
Screenshot 2024-11-12 at 9 19 40 PM

**Comment by paskal** [comment]
@umputun interesting case: this PR broke backend tests in master (fixed in #1862), but the latest commit is merge commit which doesn't touch backend so the tests were not run. No idea what to do about it aside from asking the requestor to squash commits locally.

**Comment by mgkbadola** [comment]
Let me know how can I help to resolve this

**Comment by paskal** [comment]
No need to do anything from your side @mgkbadola, it's a fault of our CI setup which doesn't highlight the problem where it should. The failing test is already fixed.

**Pull request merged**
