### PR TITLE
Fix username escape

### PR DESCRIPTION
**Pull request by Reeywhaar**
to #415 

Adds unescaping for username in main widget and last comments. (Not sure if I had to)

Screenshot 2019-08-21 at 01 51 43
Screenshot 2019-08-21 at 01 51 31

### CODE REVIEW

**Comment by Reeywhaar** [comment]
I've remove most of the commits, remains are only small fixes. Waiting for https://github.com/umputun/remark/issues/415#issuecomment-523236222

**Comment by Reeywhaar** [comment]
reverted PR to previous stage, there we have unescape only for `",',&`

**Comment by skubi** [comment]
In case somebody is wondering, gitignore content is taken from here: https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore

**Comment by paskal** [comment]
@Reeywhaar I wonder what is the current state of this PR, do you have a plan of rebasing and merging it or there are still some blockers?

**Comment by Reeywhaar** [comment]
I'm not sure what current state of username escape on server side. If this pr is still necessary. I think It easier to close this pr, and if some problem exists, just rewrite on top of current master.

**Pull request closed without merging**
