### PR TITLE
Don't allow relative links in comments

### PR DESCRIPTION
**Pull request by paskal**
(url) is a text inserted by default and never an intended URL.

That additional validation will ensure that users won't post relative links because they are rarely intended.

This is how it looks without frontend changes:

image

Backend part for #809.

### CODE REVIEW

**Comment by akellbl4** [comment]
Are we gonna throw an error in case link provided without protocol? Like `[google](google.com)`. Because it results in a link that refers to `${currentUrl}/google.com`

**Comment by paskal** [comment]
This change prohibits posting relative links. I have to think about how to parse markdown correctly, but the change is already working and can be tested. @umputun, what do you think about the whole idea of blocking the relative URLs?

**Comment by umputun** [comment]
Using relative links intentionally is an extremely rare use case. One would need to have a file server on the same subdomain as Remark42 to make any sense of this. I believe disabling such links is a good idea and will work well in 99.9% of cases.

**Review by umputun — APPROVED** [review]
LGTM

**Pull request merged**
