### PR TITLE
fix background color in dark mode

### PR DESCRIPTION
**Pull request by chuhlomin**
Fixing this:

Screen Shot 2022-07-17 at 22 45 49

### CODE REVIEW

**Comment by akellbl4** [comment]
@chuhlomin hey, thank you for contribution!
Can you please share info about browser in which this bug appears?

**Comment by chuhlomin** [comment]
@akellbl4 it's in Safari 15.5 (17613.2.7.1.8)

**Comment by akellbl4** [comment]
That's odd because I'm not getting this bug on any of those browsers.

Small explanation why the background was left without any color: We don't want to have block with comments to interfere with background of a website and it intend to be transparent. It's better to try `transparent` or `unset` in order to make the iframe injected in a site seamlessly.

**Comment by akellbl4** [comment]
I haven't dug into it but this thing is causing the problem on your site. We experienced the same problem on radio-t.com and removing the prop resolved the issue.

CleanShot 2022-07-18 at 11 07 55@2x

**Pull request closed without merging**
