### PR TITLE
user info redesign/redevelop and add dark theme

### LINKED ISSUE #920: Profile info remains light when using dark theme
## Description of the problem
Profile information and all of its comments remain light when using the dark theme.

## Steps to reproduce the problem:
1. Make sure that the dark theme is selected in the system and browser settings
2. Go to https://remark42.com/demo/
3. Click on any username

## Screenshot
image

Related issue: https://github.com/radio-t/radio-t-site/issues/216

### PR DESCRIPTION
**Pull request by akellbl4**
Resolves #920

- [x] remove dropdown on user name in login block
- [x] open user info by click on user name
- [x] replace `Logout` with icon
- [x] remove label in login block
- [x] move `Request my data removal` to user info
- [x] add additional logout button in user info
- [x] implement empty state
- [x] write tests
-  <strike>add `Hide user comments` to user info</strike> _(changing logic is needed for using in another place)_

---

The size of the styles increased because default styles were moved from HTML to CSS.

### CODE REVIEW

**Comment by paskal** [comment]
`make rundev` under M1:

```
------
 > [build-frontend 4/4] RUN cd /srv/frontend &&     if [ -z "true" ] ; then npx run-p lint test check;     else echo "skip frontend tests and lint" ; npm run build ; fi &&     rm -rf ./node_modules:
#30 0.192 skip frontend tests and lint
#30 0.285
#30 0.285 > remark42@0.16.0 build /srv/frontend
#30 0.285 > webpack --mode production
#30 0.285
#30 20.74 assets by status 758 KiB [cached] 25 assets
#30 20.74 Entrypoint embed = embed.js
#30 20.74 Entrypoint counter = counter.js
#30 20.74 Entrypoint deleteme = deleteme.js
#30 20.74 Entrypoint last-comments = last-comments.css last-comments.js 1 auxiliary asset
#30 20.74 Entrypoint remark = remark.css remark.js 2 auxiliary assets
#30 20.74 orphan modules 760 KiB [orphan] 478 modules
#30 20.74 runtime modules 15.5 KiB 29 modules
#30 20.74 cacheable modules 46.5 KiB (css/mini-extract) 1.24 MiB (javascript)
#30 20.74   modules by path ./app/ 46.5 KiB (css/mini-extract) 1.04 MiB (javascript)
#30 20.74     css modules 46.5 KiB 57 modules
#30 20.74     json modules 117 KiB 15 modules
#30 20.74     javascript modules 953 KiB
#30 20.74       modules by path ./app/components/ 5.08 KiB 8 modules
#30 20.74       6 modules
#30 20.74   modules by path ./node_modules/ 202 KiB 107 modules
#30 20.74
#30 20.74 ERROR in ./app/components/spinner/spinner.tsx 5:0-42
#30 20.74 Module not found: Error: Can't resolve './Spinner.module.css' in '/srv/frontend/app/components/spinner'
#30 20.74 resolve './Spinner.module.css' in '/srv/frontend/app/components/spinner'
#30 20.74   using description file: /srv/frontend/package.json (relative path: ./app/components/spinner)
#30 20.74     Field 'browser' doesn't contain a valid alias configuration
#30 20.74     using description file: /srv/frontend/package.json (relative path: ./app/components/spinner/Spinner.module.css)
#30 20.74       no extension
#30 20.74         Field 'browser' doesn't contain a valid alias configuration
#30 20.74         /srv/frontend/app/components/spinner/Spinner.module.css doesn't exist
#30 20.74       .ts
#30 20.74         Field 'browser' doesn't contain a valid alias configuration
#30 20.74         /srv/frontend/app/components/spinner/Spinner.module.css.ts doesn't exist
#30 20.74       .tsx
#30 20.74         Field 'browser' doesn't contain a valid alias configuration
#30 20.74         /srv/frontend/app/components/spinner/Spinner.module.css.tsx doesn't exist
#30 20.74       .js
#30 20.74         Field 'browser' doesn't contain a valid alias configuration
#30 20.74         /srv/frontend/app/components/spinner/Spinner.module.css.js doesn't exist
#30 20.74       as directory
#30 20.74         /srv/frontend/app/components/spinner/Spinner.module.css doesn't exist
#30 20.74  @ ./app/components/profile/profile.tsx 47:0-53 194:22-29
#30 20.74  @ ./app/components/profile/index.ts 1:0-26 1:0-26
#30 20.74  @ ./app/remark.tsx 43:0-45 100:37-44
#30 20.74
#30 20.74 webpack 5.36.2 compiled with 1 error in 19728 ms
#30 20.74
#30 20.74 assets by status 632 KiB [cached] 32 assets
#30 20.74 Entrypoint embed = embed.mjs
#30 20.74 Entrypoint counter = counter.mjs
#30 20.74 Entrypoint deleteme = deleteme.mjs
#30 20.74 Entrypoint last-comments = last-comments.css last-comments.mjs 1 auxiliary asset
#30 20.74 Entrypoint remark = remark.css remark.mjs 2 auxiliary assets
#30 20.74 orphan modules 760 KiB [orphan] 478 modules
#30 20.74 runtime modules 14.8 KiB 26 modules
#30 20.74 cacheable modules 46.5 KiB (css/mini-extract) 1.13 MiB (javascript)
#30 20.74   css modules 46.5 KiB
#30 20.74     modules by path ./app/components/ 43.3 KiB 55 modules
#30 20.74     modules by path ./app/styles/*.css 3.23 KiB
#30 20.74       css ./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./app/styles/custom-properties.css 1.65 KiB [built] [code generated]
#30 20.74       css ./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./app/styles/global.css 1.58 KiB [built] [code generated]
#30 20.74   javascript modules 1010 KiB
#30 20.74     modules by path ./app/ 952 KiB
#30 20.74       modules by path ./app/components/ 5.08 KiB 8 modules
#30 20.74       6 modules
#30 20.74     modules by path ./node_modules/ 57.9 KiB 13 modules
#30 20.74   json modules 147 KiB 16 modules
#30 20.74
#30 20.74 ERROR in ./app/components/spinner/spinner.tsx 5:0-42
#30 20.74 Module not found: Error: Can't resolve './Spinner.module.css' in '/srv/frontend/app/components/spinner'
#30 20.74 resolve './Spinner.module.css' in '/srv/frontend/app/components/spinner'
#30 20.74   using description file: /srv/frontend/package.json (relative path: ./app/components/spinner)
#30 20.74     Field 'browser' doesn't contain a valid alias configuration
#30 20.74     using description file: /srv/frontend/package.json (relative path: ./app/components/spinner/Spinner.module.css)
#30 20.74       no extension
#30 20.74         Field 'browser' doesn't contain a valid alias configuration
#30 20.74         /srv/frontend/app/components/spinner/Spinner.module.css doesn't exist
#30 20.74       .ts
#30 20.74         Field 'browser' doesn't contain a valid alias configuration
#30 20.74         /srv/frontend/app/components/spinner/Spinner.module.css.ts doesn't exist
#30 20.74       .tsx
#30 20.74         Field 'browser' doesn't contain a valid alias configuration
#30 20.74         /srv/frontend/app/components/spinner/Spinner.module.css.tsx doesn't exist
#30 20.74       .js
#30 20.74         Field 'browser' doesn't contain a valid alias configuration
#30 20.74         /srv/frontend/app/components/spinner/Spinner.module.css.js doesn't exist
#30 20.74       as directory
#30 20.74         /srv/frontend/app/components/spinner/Spinner.module.css doesn't exist
#30 20.74  @ ./app/components/profile/profile.tsx 47:0-53 194:22-29
#30 20.74  @ ./app/components/profile/index.ts 1:0-26 1:0-26
#30 20.74  @ ./app/remark.tsx 43:0-45 100:37-44
#30 20.74
#30 20.74 webpack 5.36.2 compiled with 1 error in 19051 ms
#30 20.88 npm ERR! code ELIFECYCLE
#30 20.88 npm ERR! errno 1
#30 20.88 npm ERR! remark42@0.16.0 build: `webpack --mode production`
#30 20.88 npm ERR! Exit status 1
#30 20.88 npm ERR!
#30 20.88 npm ERR! Failed at the remark42@0.16.0 build script.
#30 20.88 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#30 20.89
#30 20.89 npm ERR! A complete log of this run can be found in:
#30 20.89 npm ERR!     /root/.npm/_logs/2021-08-05T21_01_46_767Z-debug.log
------
executor failed running [/bin/sh -c cd /srv/frontend &&     if [ -z "$SKIP_FRONTEND_TEST" ] ; then npx run-p lint test check;     else echo "skip frontend tests and lint" ; npm run build ; fi &&     rm -rf ./node_modules]: exit code: 1
ERROR: Service 'remark42' failed to build : Build failed
make: *** [rundev] Error 1
```

**Comment by akellbl4** [comment]
@paskal it was typo, just fixed

**Review by paskal — APPROVED** [review]
image
LGTM, it works and looks neat.

**Comment by akellbl4** [comment]
User's profile:
CleanShot 2021-08-08 at 10 42 00@2x
CleanShot 2021-08-08 at 10 42 10@2x

Own profile:
CleanShot 2021-08-08 at 10 46 22@2x
CleanShot 2021-08-08 at 10 46 36@2x

Empty state:
CleanShot 2021-08-08 at 10 56 54@2x
CleanShot 2021-08-08 at 10 56 48@2x

**Review by paskal — DISMISSED** [review]

**Review by Mavrin — APPROVED** [review]
👍

**Review by Mavrin — APPROVED** [review]

**Pull request merged**
