### PR TITLE
patreon auth

### LINKED ISSUE #1125: Add support of Patreon auth
With https://github.com/go-pkgz/auth/pull/95 in place, we can add Patreon as auth provider. This provider also sets a new claim allowing us to check if the user paid a subscriber and based on this info, we can do interesting things. Probably we could add optional flags, like `subscribers-only`.

Another thing we may consider is `highlight-subscribers`. This one is mostlyty for UI to make such users visually different, for example, adding some colorful frame around the avatar. We need to extend the user's info and add this flag to the config response to make it happen.

### PR DESCRIPTION
**Pull request by romanilchyshyn**
Partially closes #1125 

Backend:
- Env vars, docs
-  `store.User` new field `PaidSub`
- `subscribers-only` env var & appropriate middleware

Frontend:
- Add new auth type
- Icon asset from [Patreon branding page](https://www.patreon.com/brand)

Need to implement on frontend:
- Subscriber highlighting
- Disable `Send` button for non-subs

### CODE REVIEW

**Comment by romanilchyshyn** [comment]
Looks like `TestMain_WithWebhook` is flaky.

**Comment by akellbl4** [comment]
> Subscriber highlighting
Disable Send button for non-subs.

1. We can add the Patreon logo right next to the username for subscribers or add them verified checkmark automatically (maybe we can color verified checkmark into the Patreon brand color)
2. That's  should be easy

**Comment by umputun** [comment]
> We can add the Patreon logo right next to the username for subscribers or add them verified checkmark automatically (maybe we can color verified checkmark into the Patreon brand color)

Adding Patreon's logo right next to the username for subscribers sounds good

**Comment by umputun** [comment]
@paskal - can you pls take a look? the PR looks fine to me, but another pair of eyes will be nice to have

**Pull request merged**
