### PR TITLE
Update dev dependencies

### PR DESCRIPTION
**Pull request by akellbl4**
Should be rebased and merged after merging of #670

### CODE REVIEW

**Comment by umputun** [comment]
smth in this PR breaks Actions checkout?

**Comment by akellbl4** [comment]
No, it shouldn't break checkout. But sometimes it happens after force push.

**Comment by umputun** [comment]
fyi: I noticed the frontend runs actions/checkout@v1. We have switched the backend to @v2. Frankly, I have no clue what the difference but maybe it could help to address this checkout issue

**Comment by akellbl4** [comment]
@Mavrin I tried to update @formatjs/cli, but it doesn't work in any minor version highest than already installed. Maybe you know why :)

**Comment by Mavrin** [comment]
I have no idea why @formatjs/cli doesn't work.

**Comment by umputun** [comment]
pls resolve conflict

**Comment by akellbl4** [comment]
@umputun done

**Pull request merged**
