### PR TITLE
make FE CI more parallel

### PR DESCRIPTION
**Pull request by pustovalov**
master:
https://github.com/pustovalov/remark42/actions/runs/224388470

time: 1m 57s

```
NODE_ENV = production
REMARK_ENV = https://demo.remark42.com
Hash: 70ab29f80338d139455d
Version: webpack 4.43.0
Time: 37223ms
```

this PR:
https://github.com/pustovalov/remark42/actions/runs/224440717

time: 1m 32s 

```
NODE_ENV = production
REMARK_ENV = https://demo.remark42.com
Hash: 70ab29f80338d139455d
Version: webpack 4.43.0
Time: 19360ms
```

### CODE REVIEW

**Review by paskal — APPROVED** [review]

**Review by akellbl4 — APPROVED** [review]

**Comment by umputun** [comment]
failed https://github.com/umputun/remark42/actions/runs/231532761

**Comment by pustovalov** [comment]
Strange, can you restart the build?

successfully: https://github.com/pustovalovv/remark42/actions/runs/231601841

**Comment by umputun** [comment]
restart helped, but it means we have a build randomly failing due to this optimization

**Comment by umputun** [comment]
tried to bump node version, still failing with the same error https://github.com/umputun/remark42/runs/1049306752?check_suite_focus=true

**Comment by pustovalov** [comment]
1 of 11 was failed: https://github.com/pustovalovv/remark42/actions

I can investigate this in a week, don't have access to my laptop right now. 

You can revert this optimization to stabilize the build. Sorry for the inconvenience

**Comment by paskal** [comment]
We had the worst problems with backend tests in the past, I propose to fix it without the revert as long as you are sure it doesn't affect end-users.

**Pull request merged**
