### PR TITLE
fix markup for subscribe block for long description

### PR DESCRIPTION
**Pull request by Mavrin**
Related issue #607 
<details>
<summary>IPhone X</summary>

127 0 0 1_9001_web_(iPhone X)

</details>

<details>
<summary>Pixel 2</summary>

127 0 0 1_9001_web_(Pixel 2)

</details>

<details>
<summary>MDPI screen</summary>

127 0 0 1_9001_web_(Laptop with MDPI screen)

</details>

### CODE REVIEW

**Comment by akellbl4** [comment]
@Mavrin could you please add screenshots how it was before fix?

**Comment by Mavrin** [comment]
@akellbl4 original issue #607

**Comment by Mavrin** [comment]
@umputun What do you think about this solution?

**Comment by umputun** [comment]
I think this could work

**Pull request merged**
