### PR TITLE
#819 Added jwt token to requests

### PR DESCRIPTION
**Pull request by madmages**
1. If X-JWT header received by any response - it will be stored in localstorage
2. If jwt is in localstorage - it will be send by each request
3. If 403 received and jwt in localstorage - it will be removed.

### CODE REVIEW

**Comment by umputun** [comment]
thx for the PR. However, I'm not sure about storing JWT in the local storage. Isn't this open the system to a whole new class of XSS attacks? And, as far as I understand, #819 didn't propose this, and all it supposed to do is "allow to login though it is indeed will be logged out after page refresh.", i.e. keep the token in the memory only.

**Comment by madmages** [comment]
Ok.
In #819 was not present restrictions for realization, so i made as i wish.
Usage of localstorage is present in couple places, i thought it`s not a problem.

Changed storage to local variable.

**Review by akellbl4 — DISMISSED** [review]
LGTM

**Comment by paskal** [comment]
If JWT token is stored in a variable which is not accessible outside of the script in question, I am OK with these changes. I am not good enough in JS to know for sure, I only know that local storage is not good for that for [multiple reasons](https://stackoverflow.com/a/44209185/961092).

**Pull request merged**
