### PR TITLE
add ukranian locale

### PR DESCRIPTION
**Pull request by Ivanezko**
based on ru.json

### CODE REVIEW

**Comment by Mavrin** [comment]
Please, add a new locale with two-letter code of the language you want to make the translation into to list in `frontend/tasks/supportedLocales.json`. More info about translation process you can find in https://remark42.com/docs/1.6/translation/

**Comment by Ivanezko** [comment]
Hello, looks like the docs (https://remark42.com/docs/1.6/translation/) miss extraction step: npm run translation:extract 

Without it translation:generate doesn’t work:

 ~/Documents/remark42/frontend  master !1  npm run translation:generate                                                                                                                                               

> remark-ui@0.1.0 translation:generate /Users/ivanezko/Documents/remark42/frontend
> node ./tasks/generateDictionary.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '../extracted-messages/messages'
Require stack:
- /Users/ivanezko/Documents/remark42/frontend/tasks/getTranslationKeys.js
- /Users/ivanezko/Documents/remark42/frontend/tasks/generateDictionary.js


Additionally, 
docker-compose -f compose-dev-frontend.yml build
Generates error even on clean clone:

NODE_ENV = production
REMARK_ENV = https://demo.remark42.com
PASS app/common/local-storage.test.ts (13.882 s)
PASS app/store/user/actions.test.ts (35.22 s)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remark-ui@0.1.0 check: `cross-env NODE_ENV=production npm run build && run-p check:*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remark-ui@0.1.0 check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-04T10_01_27_281Z-debug.log
ERROR: "check" exited with 1.
ERROR: Service 'remark42' failed to build : The command '/bin/sh -c cd /srv/frontend &&     if [ -z "$SKIP_FRONTEND_TEST" ] ; then npx run-p lint test check;     else echo "skip frontend tests and lint" ; npm run build ; fi &&     rm -rf ./node_modules' returned a non-zero code: 1

Had no success getting rid of it, could you help please?

**Comment by Ivanezko** [comment]
Screen-shots:
image
image
image
image
image

Started frontend with npm start to make screen-shots, docker buld still cant start

**Review by Mavrin — APPROVED** [review]

**Review by umputun — APPROVED** [review]
thx

**Pull request merged**
